apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  mysql_database: "ApiServerDB"
  initdb: |
    CREATE TABLE IF NOT EXISTS ApiServerDB.call_history (
    id  INTEGER PRIMARY KEY,
    time DATETIME NOT NULL,
    param VARCHAR(128),
    result VARCHAR(128),
    );
