kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 1024M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/vadim/kube-db"
